### PR TITLE
fix typo: word -> world

### PR DESCRIPTION
**Pull request by justbuchanan**

### CODE REVIEW

**Comment by fragmuffin** [comment]
Hmm... it's curious that the tests failed twice.
And Appveyor is throwing a fit about my experimental powershell code.

I'm away for a few days without a linux box, so I'll get onto this by Thursday.

@justbuchanan thanks for the fix!, I'd be happy to merge it straight away, but I'll use this as an opportunity to see what's wrong with the tests.

**Comment by justbuchanan** [comment]
Ahh that is strange, not sure what the permissions issue is about. No rush on this or the other PR I just sent - take your time. I don't know any powershell, so I can't help there, but I may have some time to look at the issues on travis-ci.

**Comment by fragmuffin** [comment]
I managed to SSH into a box running at home 😁 

Ah! it looks like it's [this change](https://github.com/msiemens/tinydb/commit/ba688394153412731215e35bb3c05b722f6a782f#diff-81b4921e895d3954bb9e95ff7204cba8R93) that's causing the problem.

We originally had problems with TravisCI because it clones the repository in a read-only way. So if anything opens a revision controlled file as write, or read/write, then the OS effectively throws this permission error.

This was "fixed" by `mock.patch`ing `__builtin__.open` so it could only open files as read-only. But the commit linked above has changed this to `codecs.open`.

No problem [edits in `vim` furiously]

**Comment by fragmuffin** [comment]
OK, Travis is happy now, but Appveyor seems to push the package list to `pip` as 1 long package name... maybe.
When using powershell to pipe to file, it seems to encode as `utf-16`, with an initial character of `'\ufeff'`.
I'm wondering if this is also happening when it's piped straight to `python -m pip`.

Anyway... appveyor stuff is always messy because I don't know how to test it on a local host.
And quite frankly, windows support is a bit of an afterthought, even though I do understand it's a significant audience, so it is important.
Anyway, I'm tired, and stuck in this hotel, I'm gonna get some sleep for now.

**Comment by justbuchanan** [comment]
Nice work! Good to see some green check marks again :). Ha, I forgot github can do that, that's pretty convenient!

**Pull request merged**
